### PR TITLE
Some re-organization of the repository

### PR DESCRIPTION
**Pull request by vijaysm**
Most of the changes are self-explanatory. The significant changes include:

1) Organizing all sources, tests, and other artifacts in their own directory structure
2) Create a setup.py packaging system to install dependencies
3) You can optionally also use requirements.txt to achieve the same effect
4) README.md is now completely updated with instructions with a complete example. The illustration provides all required commands to generate meshes, pre-process the mesh, sample fields, computation of the remapped solutions, and finally the computation of metrics for remapping algorithm

Hopefully, this cleanup didn't break anything else, but we should be much closer to tagging a release after this.

### CODE REVIEW

**Comment by kuberry** [comment]
Hi all, I think we need to consider who is the owner of this repository, to make sure it is published according to that lab/institutions policies for open source software. I don't view this as Sandia software, as it was started by @jeguerra and then forked here by @rljacob. The project lives in the CANGA org, which I think is ANL owned. 

Once we figure out the code ownership, we should switch the license to comply with that institution and remove the other author's names from the license (they can be author's for the DOI, though; and I prefer to keep it BSD3 as it is).

**Comment by ghost** [comment]
Thank you Vijay for taking care of all that housekeeping work! Everything looks good with the reorganization of the repository for me.

**Review by ghost — APPROVED** [review]

**Comment by kuberry** [comment]
The last version of numba that doesn't complain about the index slicing issue is 0.49.1. Requirement
`numba<0.50.0` captures this. 

In the future, we can try to change some of the code to work with newer versions of numba, but this will work in the meantime.

**Comment by kuberry** [comment]
Also, the last set of changes I made was to require things like `scipy>=1.0.1` instead of `scipy>=1.7` because requiring such new versions means everyone who runs `pip install -r requirements.txt` will have to reinstall numpy, scipy, etc....

**Comment by xmjiao** [comment]
Probably Qiao's pull request for #12 can be first merged into this branch, and then the requirement for numba<0.50.0 can be removed.

**Review by xmjiao — APPROVED** [review]
The changes look good to me. Thanks!

**Comment by kuberry** [comment]
I'm in the process of testing the PR with numba (0.48.0). Everything should work fine, but please don't merge until that is complete, as once it is we can relax the numba constraint in requirements to `numba>=0.48.0`.

**Comment by kuberry** [comment]
Just relaxed requirements to package versions that were available around three years ago. Verified that numba==0.48.0 works with the newest changes, so relaxed to `numba>=0.48.0`.

**Review by kuberry — APPROVED** [review]

**Comment by kuberry** [comment]
Thanks @vijaysm for reorganizing, all the README work,  and the setup script!

**Comment by vijaysm** [comment]
Thanks for checking and updating the sources @kuberry @xmjiao

**Pull request merged**
